### ISSUE TITLE
not able to install tg enhanced, tg name on odoo server

### ISSUE THREAD

**Issue by bjuarez** [ThierryGodin/odoo-tg-addons#1]
# I was trying to install this module on odoo 8  but the following errors appears, can anyone help me on this?

OpenERP Server Error

Traceback (most recent call last):
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/http.py", line 345, in dispatch
    response["result"] = self._call_function(*_self.params)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/http.py", line 217, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/http.py", line 212, in checked_call
    return self.func(_a, *_kw)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/http.py", line 529, in __call__
    return self.method(_args, *_kw)
  File "/opt/openerp-saas3/oerp-saas3/web/addons/web/controllers/main.py", line 1207, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/openerp-saas3/oerp-saas3/web/addons/web/controllers/main.py", line 1195, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/addons/base/module/module.py", line 425, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/addons/base/module/module.py", line 476, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/modules/registry.py", line 247, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/modules/loading.py", line 341, in load_modules
    loaded_modules, update_module)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/modules/loading.py", line 244, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/modules/loading.py", line 175, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/modules/loading.py", line 116, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/tools/convert.py", line 967, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/tools/convert.py", line 1053, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/tools/convert.py", line 921, in parse
    self._tags[rec.tag](self.cr, rec, n)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/tools/convert.py", line 850, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/addons/base/ir/ir_model.py", line 1010, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/addons/base/ir/ir_ui_view.py", line 177, in create
    return super(view, self).create(cr, uid, values, context)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/osv/orm.py", line 4156, in create
    self._validate(cr, user, [id_new], context)
  File "/opt/openerp-saas3/oerp-saas3/server/openerp/osv/orm.py", line 1575, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
ParseError: "ValidateError
The field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<field name="name">' cannot be located in parent view

Error context:
View `view.tg.partner.tree`
[view_id: 869, xml_id: n/a, model: res.partner, parent_id: 121]" while parsing /opt/openerp/oerp/myaddons/tg_partner_firstname/tg_partner_view.xml:30, near
<record model="ir.ui.view" id="view_tg_partner_tree">
            <field name="model">res.partner</field>
            <field name="name">view.tg.partner.tree</field>
            <field name="view_type">tree</field>
            <field name="inherit_id" ref="base.view_partner_tree"/>
            <field name="arch" type="xml">
                <data><field name="name" position="after">
                    <field name="firstname"/>
                    <field name="zip"/>
                </field>
                <field name="phone" position="after">
                    <field name="mobile"/>
                </field>
                <field name="email" position="after">  
                    <field name="country"/>
                </field>
            </data></field>
        </record>

**Comment by ly2ly** [comment]
hello,
This module is only for OpenERP V7. So you need to make a new version for Odoo V8 in order to work with it

**Comment by bjuarez** [comment]
And thats like asking a stone to fly :( 
Thank you anyway for the prompt response.
